require: rubocop-rspec
AllCops:
  Excludes:
    - db/*
    - db/migrate/*
    - bin/*
    - Gemfile
    - config/**/*
    - config/*

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Documentation:
  Enabled: false
